apiVersion: v1
kind: Service
metadata:
  name: vordu-service
  labels:
    app: vordu
spec:
  selector:
    app: vordu
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
